"""add a tabela de twoFactorChallenge

Revision ID: 0767084ae605
Revises: 66c5410f8a75
Create Date: 2026-09-19 18:17:27.945394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0767084ae605'
down_revision: Union[str, Sequence[str], None] = '66c5410f8a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_factor_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('expira_as', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_as', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_challenges_token_hash'), 'two_factor_challenges', ['token_hash'], unique=True)
    op.create_index(op.f('ix_two_factor_challenges_user_id'), 'two_factor_challenges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_two_factor_challenges_user_id'), table_name='two_factor_challenges')
    op.drop_index(op.f('ix_two_factor_challenges_token_hash'), table_name='two_factor_challenges')
    op.drop_table('two_factor_challenges')
    # ### end Alembic commands ###
