"""remocao da categoria das noticias e os relacionamentos

Revision ID: 284ff65e094a
Revises: 
Create Date: 2026-09-25 07:47:59.685301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284ff65e094a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('categoria', sa.String(length=20), nullable=False))
    op.drop_column('noticias', 'categoria_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('noticias', 'categoria')
    # ### end Alembic commands ###
