"""última vez que foi notificado por quota em atraso: notificado_quota_atraso_em na tabela user

Revision ID: 33de9d2778b6
Revises: 83d5f0e7d32c
Create Date: 2026-09-10 16:51:01.314179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33de9d2778b6'
down_revision: Union[str, Sequence[str], None] = '83d5f0e7d32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagamentos_quota', 'data_expiracao_quota')
    op.drop_column('pagamentos_quota', 'notificado_quota_atraso_em')
    op.add_column('users', sa.Column('data_expiracao_quota', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('notificado_quota_atraso_em', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notificado_quota_atraso_em')
    op.drop_column('users', 'data_expiracao_quota')
    op.add_column('pagamentos_quota', sa.Column('notificado_quota_atraso_em', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('pagamentos_quota', sa.Column('data_expiracao_quota', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
