"""resolvendo problemas de inconpatibilidade no login  e login/2fa

Revision ID: 3fe48506ec7d
Revises: bb95500e7826
Create Date: 2026-09-21 09:22:00.493966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe48506ec7d'
down_revision: Union[str, Sequence[str], None] = 'bb95500e7826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
