"""add todos as tabelas a nova database

Revision ID: 4a51839917bc
Revises: 
Create Date: 2026-09-24 08:10:52.370839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a51839917bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticia_categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_permissoes_id'), 'permissoes', ['id'], unique=False)
    op.create_table('provincias',
    sa.Column('nome_provincia', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincias_id'), 'provincias', ['id'], unique=False)
    op.create_index(op.f('ix_provincias_nome_provincia'), 'provincias', ['nome_provincia'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('municipios',
    sa.Column('nome_municipio', sa.String(length=100), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_municipio', 'id_provincia', name='uq_municipio_provincia')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    op.create_table('role_permissoes',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permissoes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissoes_id'], ['permissoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permissoes_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nif', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('genero', sa.Enum('MULHER', 'HOMEM', name='genero'), nullable=False),
    sa.Column('cadastrar_militante', sa.Enum('MILITANTE', 'SIMPATIZANTE', name='cadastrarcomo'), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('foi_militante', sa.Boolean(), nullable=True),
    sa.Column('militante_numero', sa.String(length=20), nullable=True),
    sa.Column('partilha_dados', sa.Boolean(), nullable=False),
    sa.Column('cookies_personalizacao', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('notificacoes_gerais', sa.Boolean(), nullable=False),
    sa.Column('comunicados_oficiais', sa.Boolean(), nullable=False),
    sa.Column('eventos_mobilizacoes', sa.Boolean(), nullable=False),
    sa.Column('contribuicoes_quota', sa.Boolean(), nullable=False),
    sa.Column('noticias_partido', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('password_alterado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_expiracao_quota', sa.Date(), nullable=True),
    sa.Column('notificado_quota_atraso_em', sa.Date(), nullable=True),
    sa.Column('estado_civil', sa.Enum('SOLTEIRO', 'CASADO', 'DIVORCIADO', 'VIUVO', name='estadocivil'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tentativa_acertos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentativas_apos_bloqueio', sa.Integer(), nullable=True),
    sa.Column('bloqueado_permanente', sa.Boolean(), nullable=True),
    sa.CheckConstraint("data_nascimento <= CURRENT_DATE - INTERVAL '18 years'", name='check_maior_idade'),
    sa.CheckConstraint('email = lower(email) AND length(trim(email)) > 0', name='check_email_valido'),
    sa.CheckConstraint('length(trim(telefone)) > 0', name='check_telefone_preenchido'),
    sa.CheckConstraint('nif = upper(nif) AND length(trim(nif)) = 14', name='check_nif_angola'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_militante_numero'), 'users', ['militante_numero'], unique=True)
    op.create_index(op.f('ix_users_nif'), 'users', ['nif'], unique=True)
    op.create_table('admin_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_scopes_id'), 'admin_scopes', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accao', sa.String(length=50), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.String(length=50), nullable=False),
    sa.Column('ultimo_valores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('novo_valores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_endereco', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('cartao_militantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('militante_numero', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=False),
    sa.Column('url_qrcode', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gerado_por', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_assinatura', sa.TEXT(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gerado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartao_militantes_id'), 'cartao_militantes', ['id'], unique=False)
    op.create_index(op.f('ix_cartao_militantes_militante_numero'), 'cartao_militantes', ['militante_numero'], unique=True)
    op.create_index(op.f('ix_cartao_militantes_user_id'), 'cartao_militantes', ['user_id'], unique=False)
    op.create_table('doacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('quantia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('MCX', 'TRANSFERENCIA', 'IBAN', name='metodopagamentoenum'), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('id_transacao', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='donationstatusenum'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('data_doacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aprovado_por', sa.UUID(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recibo_url', sa.TEXT(), nullable=True),
    sa.Column('recibo_gerado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantia > 0', name='ck_doacao_quantia_positiva'),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doacoes_data_doacao'), 'doacoes', ['data_doacao'], unique=False)
    op.create_index(op.f('ix_doacoes_id_transacao'), 'doacoes', ['id_transacao'], unique=True)
    op.create_index(op.f('ix_doacoes_referencia'), 'doacoes', ['referencia'], unique=True)
    op.create_index(op.f('ix_doacoes_status'), 'doacoes', ['status'], unique=False)
    op.create_index('ix_doacoes_status_data', 'doacoes', ['status', 'data_doacao'], unique=False)
    op.create_index(op.f('ix_doacoes_user_id'), 'doacoes', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('localizacao', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('max_participantes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'PUBLICADO', 'CANCELADO', 'CONCLUIDO', name='eventstatusenum'), nullable=False),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('max_participantes > 0', name='check_max_participantes_positivo'),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('mensagens_suporte',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.Enum('PAGAMENTOS_QUOTAS', 'SUGESTOES', 'SUPORTE_TECNICO', 'PROBLEMA_DE_CONTA', 'OUTROS', name='categoriamensagemsuporte'), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.TEXT(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_suporte_admin_id'), 'mensagens_suporte', ['admin_id'], unique=False)
    op.create_index(op.f('ix_mensagens_suporte_user_id'), 'mensagens_suporte', ['user_id'], unique=False)
    op.create_table('movimentos_financeiros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('DOACAO', 'QUOTA', 'DESPESA', name='tipomovimentoenum'), nullable=False),
    sa.Column('origem_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('quantia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('status_anterior', sa.String(length=20), nullable=True),
    sa.Column('status_novo', sa.String(length=20), nullable=False),
    sa.Column('acao', sa.Enum('CRIADA', 'APROVADA', 'REJEITADA', 'CANCELADA', 'ATUALIZADA', name='acaomovimentoenum'), nullable=False),
    sa.Column('ator_id', sa.UUID(), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mov_acao_data', 'movimentos_financeiros', ['acao', 'criado_em'], unique=False)
    op.create_index('ix_mov_tipo_origem', 'movimentos_financeiros', ['tipo', 'origem_id'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_acao'), 'movimentos_financeiros', ['acao'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_criado_em'), 'movimentos_financeiros', ['criado_em'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_origem_id'), 'movimentos_financeiros', ['origem_id'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_tipo'), 'movimentos_financeiros', ['tipo'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_user_id'), 'movimentos_financeiros', ['user_id'], unique=False)
    op.create_table('noticias',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('subtitulo', sa.String(length=255), nullable=True),
    sa.Column('lead', sa.TEXT(), nullable=True),
    sa.Column('corpo', sa.TEXT(), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('publicado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['noticia_categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noticias_id'), 'noticias', ['id'], unique=False)
    op.create_index(op.f('ix_noticias_slug'), 'noticias', ['slug'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.TEXT(), nullable=False),
    sa.Column('motivo', sa.TEXT(), nullable=True),
    sa.Column('lido_as', sa.DateTime(), nullable=True),
    sa.Column('destinatario', sa.String(length=20), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_admin_id'), 'notifications', ['admin_id'], unique=False)
    op.create_index(op.f('ix_notifications_destinatario'), 'notifications', ['destinatario'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('pagamentos_quota',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quantia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('meses_pagar', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('MCX', 'TRANSFERENCIA', 'IBAN', name='metodopagamentoenum'), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('id_transacao', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='quotastatusenum'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aprovado_por', sa.UUID(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantia > 0', name='ck_quota_quantia_positiva'),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_quota_data_pagamento'), 'pagamentos_quota', ['data_pagamento'], unique=False)
    op.create_index(op.f('ix_pagamentos_quota_id_transacao'), 'pagamentos_quota', ['id_transacao'], unique=True)
    op.create_index(op.f('ix_pagamentos_quota_periodo'), 'pagamentos_quota', ['periodo'], unique=False)
    op.create_index(op.f('ix_pagamentos_quota_status'), 'pagamentos_quota', ['status'], unique=False)
    op.create_index(op.f('ix_pagamentos_quota_user_id'), 'pagamentos_quota', ['user_id'], unique=False)
    op.create_index('ix_quota_status_data', 'pagamentos_quota', ['status', 'data_pagamento'], unique=False)
    op.create_index('ix_quota_user_periodo', 'pagamentos_quota', ['user_id', 'periodo'], unique=False)
    op.create_index('uq_pagamento_quota_user_pending', 'pagamentos_quota', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"), sqlite_where=sa.text("status = 'PENDING'"))
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('solicitacoes_cartao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='statussolicitacao'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_cartao_id'), 'solicitacoes_cartao', ['id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_cartao_status'), 'solicitacoes_cartao', ['status'], unique=False)
    op.create_index(op.f('ix_solicitacoes_cartao_user_id'), 'solicitacoes_cartao', ['user_id'], unique=False)
    op.create_index('uq_cartao_pendente_usuario', 'solicitacoes_cartao', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDENTE'"))
    op.create_table('solicitacoes_fundo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('finalidade', sa.Enum('EVENTOS', 'FORMACOES', 'COMICIOS', 'MATERIAL', 'TRANSPORTE', 'SEDE', 'OUTRO', name='finalidadefundoenum'), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('quantia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='despesastatusenum'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('solicitado_por', sa.UUID(), nullable=True),
    sa.Column('aprovado_por', sa.UUID(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantia > 0', name='ck_solicitacao_quantia_positiva'),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitado_por'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_solicitacao_prov_status', 'solicitacoes_fundo', ['provincia_id', 'status'], unique=False)
    op.create_index(op.f('ix_solicitacoes_fundo_data_solicitacao'), 'solicitacoes_fundo', ['data_solicitacao'], unique=False)
    op.create_index(op.f('ix_solicitacoes_fundo_municipio_id'), 'solicitacoes_fundo', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_fundo_provincia_id'), 'solicitacoes_fundo', ['provincia_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_fundo_status'), 'solicitacoes_fundo', ['status'], unique=False)
    op.create_table('solicitacoes_militancia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='statussolicitacaomilitancia'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_militancia_id'), 'solicitacoes_militancia', ['id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_militancia_status'), 'solicitacoes_militancia', ['status'], unique=False)
    op.create_index(op.f('ix_solicitacoes_militancia_user_id'), 'solicitacoes_militancia', ['user_id'], unique=False)
    op.create_index('uq_solicitacao_pendente_usuario', 'solicitacoes_militancia', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDENTE'"))
    op.create_table('two_factor_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('expira_as', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_as', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_challenges_token_hash'), 'two_factor_challenges', ['token_hash'], unique=True)
    op.create_index(op.f('ix_two_factor_challenges_user_id'), 'two_factor_challenges', ['user_id'], unique=False)
    op.create_table('user_backup_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('code_hash', sa.TEXT(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_backup_codes_id'), 'user_backup_codes', ['id'], unique=False)
    op.create_index(op.f('ix_user_backup_codes_user_id'), 'user_backup_codes', ['user_id'], unique=False)
    op.create_table('user_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('utilizado', sa.Boolean(), nullable=False),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('utilizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_refresh_tokens_token_jti'), 'user_refresh_tokens', ['token_jti'], unique=True)
    op.create_index(op.f('ix_user_refresh_tokens_user_id'), 'user_refresh_tokens', ['user_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('events_id', sa.UUID(), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'events_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_user_refresh_tokens_user_id'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_token_jti'), table_name='user_refresh_tokens')
    op.drop_table('user_refresh_tokens')
    op.drop_index(op.f('ix_user_backup_codes_user_id'), table_name='user_backup_codes')
    op.drop_index(op.f('ix_user_backup_codes_id'), table_name='user_backup_codes')
    op.drop_table('user_backup_codes')
    op.drop_index(op.f('ix_two_factor_challenges_user_id'), table_name='two_factor_challenges')
    op.drop_index(op.f('ix_two_factor_challenges_token_hash'), table_name='two_factor_challenges')
    op.drop_table('two_factor_challenges')
    op.drop_index('uq_solicitacao_pendente_usuario', table_name='solicitacoes_militancia', postgresql_where=sa.text("status = 'PENDENTE'"))
    op.drop_index(op.f('ix_solicitacoes_militancia_user_id'), table_name='solicitacoes_militancia')
    op.drop_index(op.f('ix_solicitacoes_militancia_status'), table_name='solicitacoes_militancia')
    op.drop_index(op.f('ix_solicitacoes_militancia_id'), table_name='solicitacoes_militancia')
    op.drop_table('solicitacoes_militancia')
    op.drop_index(op.f('ix_solicitacoes_fundo_status'), table_name='solicitacoes_fundo')
    op.drop_index(op.f('ix_solicitacoes_fundo_provincia_id'), table_name='solicitacoes_fundo')
    op.drop_index(op.f('ix_solicitacoes_fundo_municipio_id'), table_name='solicitacoes_fundo')
    op.drop_index(op.f('ix_solicitacoes_fundo_data_solicitacao'), table_name='solicitacoes_fundo')
    op.drop_index('ix_solicitacao_prov_status', table_name='solicitacoes_fundo')
    op.drop_table('solicitacoes_fundo')
    op.drop_index('uq_cartao_pendente_usuario', table_name='solicitacoes_cartao', postgresql_where=sa.text("status = 'PENDENTE'"))
    op.drop_index(op.f('ix_solicitacoes_cartao_user_id'), table_name='solicitacoes_cartao')
    op.drop_index(op.f('ix_solicitacoes_cartao_status'), table_name='solicitacoes_cartao')
    op.drop_index(op.f('ix_solicitacoes_cartao_id'), table_name='solicitacoes_cartao')
    op.drop_table('solicitacoes_cartao')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('uq_pagamento_quota_user_pending', table_name='pagamentos_quota', postgresql_where=sa.text("status = 'PENDING'"), sqlite_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_quota_user_periodo', table_name='pagamentos_quota')
    op.drop_index('ix_quota_status_data', table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_user_id'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_status'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_periodo'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_id_transacao'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_data_pagamento'), table_name='pagamentos_quota')
    op.drop_table('pagamentos_quota')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_destinatario'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_admin_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_noticias_slug'), table_name='noticias')
    op.drop_index(op.f('ix_noticias_id'), table_name='noticias')
    op.drop_table('noticias')
    op.drop_index(op.f('ix_movimentos_financeiros_user_id'), table_name='movimentos_financeiros')
    op.drop_index(op.f('ix_movimentos_financeiros_tipo'), table_name='movimentos_financeiros')
    op.drop_index(op.f('ix_movimentos_financeiros_origem_id'), table_name='movimentos_financeiros')
    op.drop_index(op.f('ix_movimentos_financeiros_criado_em'), table_name='movimentos_financeiros')
    op.drop_index(op.f('ix_movimentos_financeiros_acao'), table_name='movimentos_financeiros')
    op.drop_index('ix_mov_tipo_origem', table_name='movimentos_financeiros')
    op.drop_index('ix_mov_acao_data', table_name='movimentos_financeiros')
    op.drop_table('movimentos_financeiros')
    op.drop_index(op.f('ix_mensagens_suporte_user_id'), table_name='mensagens_suporte')
    op.drop_index(op.f('ix_mensagens_suporte_admin_id'), table_name='mensagens_suporte')
    op.drop_table('mensagens_suporte')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_doacoes_user_id'), table_name='doacoes')
    op.drop_index('ix_doacoes_status_data', table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_status'), table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_referencia'), table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_id_transacao'), table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_data_doacao'), table_name='doacoes')
    op.drop_table('doacoes')
    op.drop_index(op.f('ix_cartao_militantes_user_id'), table_name='cartao_militantes')
    op.drop_index(op.f('ix_cartao_militantes_militante_numero'), table_name='cartao_militantes')
    op.drop_index(op.f('ix_cartao_militantes_id'), table_name='cartao_militantes')
    op.drop_table('cartao_militantes')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_scopes_id'), table_name='admin_scopes')
    op.drop_table('admin_scopes')
    op.drop_index(op.f('ix_users_nif'), table_name='users')
    op.drop_index(op.f('ix_users_militante_numero'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissoes')
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_provincias_nome_provincia'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_id'), table_name='provincias')
    op.drop_table('provincias')
    op.drop_index(op.f('ix_permissoes_id'), table_name='permissoes')
    op.drop_table('permissoes')
    op.drop_table('noticia_categorias')
    # ### end Alembic commands ###
