"""add o endpoint de /user/email-recuperacao

Revision ID: 5c756d3e7a3f
Revises: aed86cf48426
Create Date: 2026-09-27 01:17:40.810990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c756d3e7a3f'
down_revision: Union[str, Sequence[str], None] = 'aed86cf48426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_recuperacao', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email_recuperacao'), 'users', ['email_recuperacao'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_recuperacao'), table_name='users')
    op.drop_column('users', 'email_recuperacao')
    # ### end Alembic commands ###
