"""add novos tipos de categorias ao listar as notificacoes

Revision ID: 66c5410f8a75
Revises: 33de9d2778b6
Create Date: 2026-09-13 08:50:01.043811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c5410f8a75'
down_revision: Union[str, Sequence[str], None] = '33de9d2778b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
