"""add as novas tabelas na base de dados

Revision ID: 68c088b232cd
Revises: c24c707985c8
Create Date: 2026-09-08 18:08:12.469010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c088b232cd'
down_revision: Union[str, Sequence[str], None] = 'c24c707985c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos_quota', sa.Column('meses_pagar', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagamentos_quota', 'meses_pagar')
    # ### end Alembic commands ###
