"""última vez que foi notificado por quota em atraso: notificado_quota_atraso_em

Revision ID: 83d5f0e7d32c
Revises: 93779155627a
Create Date: 2026-09-10 15:07:43.575466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d5f0e7d32c'
down_revision: Union[str, Sequence[str], None] = '93779155627a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos_quota', sa.Column('notificado_quota_atraso_em', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagamentos_quota', 'notificado_quota_atraso_em')
    # ### end Alembic commands ###
