"""add o endpoint de suport tecnico

Revision ID: 8e680f4c9623
Revises: 
Create Date: 2026-09-01 14:01:17.597754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e680f4c9623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_suporte',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.Enum('PAGAMENTOS_QUOTAS', 'SUGESTOES', 'SUPORTE_TECNICO', 'PROBLEMA_DE_CONTA', 'OUTROS', name='categoriamensagemsuporte'), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.TEXT(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_suporte_admin_id'), 'mensagens_suporte', ['admin_id'], unique=False)
    op.create_index(op.f('ix_mensagens_suporte_user_id'), 'mensagens_suporte', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_suporte_user_id'), table_name='mensagens_suporte')
    op.drop_index(op.f('ix_mensagens_suporte_admin_id'), table_name='mensagens_suporte')
    op.drop_table('mensagens_suporte')
    # ### end Alembic commands ###
