"""add as novas tabelas na base de dados

Revision ID: a6cb11dadaf1
Revises: c726fc49787f
Create Date: 2026-09-10 12:24:52.582522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cb11dadaf1'
down_revision: Union[str, Sequence[str], None] = 'c726fc49787f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos_quota', sa.Column('data_expiracao_quota', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagamentos_quota', 'data_expiracao_quota')
    # ### end Alembic commands ###
