"""add a coluna de tipo_usuario a tabela de Notificacoes

Revision ID: a83d513fd2e6
Revises: e5168b07ccbd
Create Date: 2026-10-03 19:58:29.342451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83d513fd2e6'
down_revision: Union[str, Sequence[str], None] = 'e5168b07ccbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('tipo_usuario', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_notifications_tipo_usuario'), 'notifications', ['tipo_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_tipo_usuario'), table_name='notifications')
    op.drop_column('notifications', 'tipo_usuario')
    # ### end Alembic commands ###
