"""add o campo de codigo_verificacao_email na tabela de User

Revision ID: aed86cf48426
Revises: 284ff65e094a
Create Date: 2026-09-26 14:40:41.054836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed86cf48426'
down_revision: Union[str, Sequence[str], None] = '284ff65e094a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noticias', 'categoria',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('users', sa.Column('codigo_verificacao_email', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'codigo_verificacao_email')
    op.alter_column('noticias', 'categoria',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
