"""add challege2FA

Revision ID: bb95500e7826
Revises: 0767084ae605
Create Date: 2026-09-21 08:59:50.025317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb95500e7826'
down_revision: Union[str, Sequence[str], None] = '0767084ae605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_pagamento_quota_user_pending', 'pagamentos_quota', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"), sqlite_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pagamento_quota_user_pending', table_name='pagamentos_quota', postgresql_where=sa.text("status = 'PENDING'"), sqlite_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###
