"""add a tabela de doacoes

Revision ID: c24c707985c8
Revises: f0e1285eb13a
Create Date: 2026-09-08 14:25:27.689160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c24c707985c8'
down_revision: Union[str, Sequence[str], None] = 'f0e1285eb13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('quantia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('MCX', 'TRANSFERENCIA', 'IBAN', name='metodopagamentoenum'), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('id_transacao', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='donationstatusenum'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('data_doacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aprovado_por', sa.UUID(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recibo_url', sa.TEXT(), nullable=True),
    sa.Column('recibo_gerado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantia > 0', name='ck_doacao_quantia_positiva'),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doacoes_data_doacao'), 'doacoes', ['data_doacao'], unique=False)
    op.create_index(op.f('ix_doacoes_id_transacao'), 'doacoes', ['id_transacao'], unique=True)
    op.create_index(op.f('ix_doacoes_referencia'), 'doacoes', ['referencia'], unique=True)
    op.create_index(op.f('ix_doacoes_status'), 'doacoes', ['status'], unique=False)
    op.create_index('ix_doacoes_status_data', 'doacoes', ['status', 'data_doacao'], unique=False)
    op.create_index(op.f('ix_doacoes_user_id'), 'doacoes', ['user_id'], unique=False)
    op.create_table('movimentos_financeiros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('DOACAO', 'QUOTA', 'DESPESA', name='tipomovimentoenum'), nullable=False),
    sa.Column('origem_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('quantia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('status_anterior', sa.String(length=20), nullable=True),
    sa.Column('status_novo', sa.String(length=20), nullable=False),
    sa.Column('acao', sa.Enum('CRIADA', 'APROVADA', 'REJEITADA', 'CANCELADA', 'ATUALIZADA', name='acaomovimentoenum'), nullable=False),
    sa.Column('ator_id', sa.UUID(), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mov_acao_data', 'movimentos_financeiros', ['acao', 'criado_em'], unique=False)
    op.create_index('ix_mov_tipo_origem', 'movimentos_financeiros', ['tipo', 'origem_id'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_acao'), 'movimentos_financeiros', ['acao'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_criado_em'), 'movimentos_financeiros', ['criado_em'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_origem_id'), 'movimentos_financeiros', ['origem_id'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_tipo'), 'movimentos_financeiros', ['tipo'], unique=False)
    op.create_index(op.f('ix_movimentos_financeiros_user_id'), 'movimentos_financeiros', ['user_id'], unique=False)
    op.create_table('pagamentos_quota',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quantia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('MCX', 'TRANSFERENCIA', 'IBAN', name='metodopagamentoenum'), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('id_transacao', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='quotastatusenum'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aprovado_por', sa.UUID(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantia > 0', name='ck_quota_quantia_positiva'),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_quota_data_pagamento'), 'pagamentos_quota', ['data_pagamento'], unique=False)
    op.create_index(op.f('ix_pagamentos_quota_id_transacao'), 'pagamentos_quota', ['id_transacao'], unique=True)
    op.create_index(op.f('ix_pagamentos_quota_periodo'), 'pagamentos_quota', ['periodo'], unique=False)
    op.create_index(op.f('ix_pagamentos_quota_referencia'), 'pagamentos_quota', ['referencia'], unique=True)
    op.create_index(op.f('ix_pagamentos_quota_status'), 'pagamentos_quota', ['status'], unique=False)
    op.create_index(op.f('ix_pagamentos_quota_user_id'), 'pagamentos_quota', ['user_id'], unique=False)
    op.create_index('ix_quota_status_data', 'pagamentos_quota', ['status', 'data_pagamento'], unique=False)
    op.create_index('ix_quota_user_periodo', 'pagamentos_quota', ['user_id', 'periodo'], unique=False)
    op.create_table('solicitacoes_fundo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('finalidade', sa.Enum('EVENTOS', 'FORMACOES', 'COMICIOS', 'MATERIAL', 'TRANSPORTE', 'SEDE', 'OUTRO', name='finalidadefundoenum'), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('quantia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='despesastatusenum'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('solicitado_por', sa.UUID(), nullable=True),
    sa.Column('aprovado_por', sa.UUID(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantia > 0', name='ck_solicitacao_quantia_positiva'),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitado_por'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_solicitacao_prov_status', 'solicitacoes_fundo', ['provincia_id', 'status'], unique=False)
    op.create_index(op.f('ix_solicitacoes_fundo_data_solicitacao'), 'solicitacoes_fundo', ['data_solicitacao'], unique=False)
    op.create_index(op.f('ix_solicitacoes_fundo_municipio_id'), 'solicitacoes_fundo', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_fundo_provincia_id'), 'solicitacoes_fundo', ['provincia_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_fundo_status'), 'solicitacoes_fundo', ['status'], unique=False)
    op.add_column('notifications', sa.Column('motivo', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'motivo')
    op.drop_index(op.f('ix_solicitacoes_fundo_status'), table_name='solicitacoes_fundo')
    op.drop_index(op.f('ix_solicitacoes_fundo_provincia_id'), table_name='solicitacoes_fundo')
    op.drop_index(op.f('ix_solicitacoes_fundo_municipio_id'), table_name='solicitacoes_fundo')
    op.drop_index(op.f('ix_solicitacoes_fundo_data_solicitacao'), table_name='solicitacoes_fundo')
    op.drop_index('ix_solicitacao_prov_status', table_name='solicitacoes_fundo')
    op.drop_table('solicitacoes_fundo')
    op.drop_index('ix_quota_user_periodo', table_name='pagamentos_quota')
    op.drop_index('ix_quota_status_data', table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_user_id'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_status'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_referencia'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_periodo'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_id_transacao'), table_name='pagamentos_quota')
    op.drop_index(op.f('ix_pagamentos_quota_data_pagamento'), table_name='pagamentos_quota')
    op.drop_table('pagamentos_quota')
    op.drop_index(op.f('ix_movimentos_financeiros_user_id'), table_name='movimentos_financeiros')
    op.drop_index(op.f('ix_movimentos_financeiros_tipo'), table_name='movimentos_financeiros')
    op.drop_index(op.f('ix_movimentos_financeiros_origem_id'), table_name='movimentos_financeiros')
    op.drop_index(op.f('ix_movimentos_financeiros_criado_em'), table_name='movimentos_financeiros')
    op.drop_index(op.f('ix_movimentos_financeiros_acao'), table_name='movimentos_financeiros')
    op.drop_index('ix_mov_tipo_origem', table_name='movimentos_financeiros')
    op.drop_index('ix_mov_acao_data', table_name='movimentos_financeiros')
    op.drop_table('movimentos_financeiros')
    op.drop_index(op.f('ix_doacoes_user_id'), table_name='doacoes')
    op.drop_index('ix_doacoes_status_data', table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_status'), table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_referencia'), table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_id_transacao'), table_name='doacoes')
    op.drop_index(op.f('ix_doacoes_data_doacao'), table_name='doacoes')
    op.drop_table('doacoes')
    # ### end Alembic commands ###
