"""add as novas tabelas na base de dados

Revision ID: c726fc49787f
Revises: 68c088b232cd
Create Date: 2026-09-10 11:47:20.178929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c726fc49787f'
down_revision: Union[str, Sequence[str], None] = '68c088b232cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamentos_quota_referencia'), table_name='pagamentos_quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pagamentos_quota_referencia'), 'pagamentos_quota', ['referencia'], unique=True)
    # ### end Alembic commands ###
