"""add all tables

Revision ID: c96acdb78d86
Revises: 
Create Date: 2026-08-28 06:12:00.285467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96acdb78d86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticia_categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_permissoes_id'), 'permissoes', ['id'], unique=False)
    op.create_table('provincias',
    sa.Column('nome_provincia', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincias_id'), 'provincias', ['id'], unique=False)
    op.create_index(op.f('ix_provincias_nome_provincia'), 'provincias', ['nome_provincia'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('municipios',
    sa.Column('nome_municipio', sa.String(length=100), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_municipio', 'id_provincia', name='uq_municipio_provincia')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    op.create_table('role_permissoes',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permissoes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissoes_id'], ['permissoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permissoes_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nif', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('genero', sa.Enum('MULHER', 'HOMEM', name='genero'), nullable=False),
    sa.Column('cadastrar_militante', sa.Enum('MILITANTE', 'SIMPATIZANTE', name='cadastrarcomo'), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('foi_militante', sa.Boolean(), nullable=True),
    sa.Column('militante_numero', sa.String(length=20), nullable=True),
    sa.Column('partilha_dados', sa.Boolean(), nullable=False),
    sa.Column('cookies_personalizacao', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('notificacoes_gerais', sa.Boolean(), nullable=False),
    sa.Column('comunicados_oficiais', sa.Boolean(), nullable=False),
    sa.Column('eventos_mobilizacoes', sa.Boolean(), nullable=False),
    sa.Column('contribuicoes_quota', sa.Boolean(), nullable=False),
    sa.Column('noticias_partido', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('password_alterado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado_civil', sa.Enum('SOLTEIRO', 'CASADO', 'DIVORCIADO', 'VIUVO', name='estadocivil'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tentativa_acertos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentativas_apos_bloqueio', sa.Integer(), nullable=True),
    sa.Column('bloqueado_permanente', sa.Boolean(), nullable=True),
    sa.CheckConstraint("data_nascimento <= CURRENT_DATE - INTERVAL '18 years'", name='check_maior_idade'),
    sa.CheckConstraint('email = lower(email) AND length(trim(email)) > 0', name='check_email_valido'),
    sa.CheckConstraint('length(trim(telefone)) > 0', name='check_telefone_preenchido'),
    sa.CheckConstraint('nif = upper(nif) AND length(trim(nif)) = 14', name='check_nif_angola'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_militante_numero'), 'users', ['militante_numero'], unique=True)
    op.create_index(op.f('ix_users_nif'), 'users', ['nif'], unique=True)
    op.create_table('admin_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_scopes_id'), 'admin_scopes', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accao', sa.String(length=50), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.String(length=50), nullable=False),
    sa.Column('ultimo_valores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('novo_valores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_endereco', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('cartao_militantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('militante_numero', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=False),
    sa.Column('url_qrcode', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gerado_por', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_assinatura', sa.TEXT(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gerado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartao_militantes_id'), 'cartao_militantes', ['id'], unique=False)
    op.create_index(op.f('ix_cartao_militantes_militante_numero'), 'cartao_militantes', ['militante_numero'], unique=True)
    op.create_index(op.f('ix_cartao_militantes_user_id'), 'cartao_militantes', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('localizacao', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('max_participantes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'PUBLICADO', 'CANCELADO', 'CONCLUIDO', name='eventstatusenum'), nullable=False),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('max_participantes > 0', name='check_max_participantes_positivo'),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('noticias',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('subtitulo', sa.String(length=255), nullable=True),
    sa.Column('lead', sa.TEXT(), nullable=True),
    sa.Column('corpo', sa.TEXT(), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('publicado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['noticia_categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noticias_id'), 'noticias', ['id'], unique=False)
    op.create_index(op.f('ix_noticias_slug'), 'noticias', ['slug'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.TEXT(), nullable=False),
    sa.Column('lido_as', sa.DateTime(), nullable=True),
    sa.Column('destinatario', sa.String(length=20), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_admin_id'), 'notifications', ['admin_id'], unique=False)
    op.create_index(op.f('ix_notifications_destinatario'), 'notifications', ['destinatario'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('solicitacoes_cartao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='statussolicitacao'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_cartao_id'), 'solicitacoes_cartao', ['id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_cartao_status'), 'solicitacoes_cartao', ['status'], unique=False)
    op.create_index(op.f('ix_solicitacoes_cartao_user_id'), 'solicitacoes_cartao', ['user_id'], unique=False)
    op.create_index('uq_cartao_pendente_usuario', 'solicitacoes_cartao', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDENTE'"))
    op.create_table('solicitacoes_militancia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='statussolicitacaomilitancia'), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_militancia_id'), 'solicitacoes_militancia', ['id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_militancia_status'), 'solicitacoes_militancia', ['status'], unique=False)
    op.create_index(op.f('ix_solicitacoes_militancia_user_id'), 'solicitacoes_militancia', ['user_id'], unique=False)
    op.create_index('uq_solicitacao_pendente_usuario', 'solicitacoes_militancia', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDENTE'"))
    op.create_table('user_backup_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('code_hash', sa.TEXT(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_backup_codes_id'), 'user_backup_codes', ['id'], unique=False)
    op.create_index(op.f('ix_user_backup_codes_user_id'), 'user_backup_codes', ['user_id'], unique=False)
    op.create_table('user_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('utilizado', sa.Boolean(), nullable=False),
    sa.Column('criado_as', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('utilizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_refresh_tokens_token_jti'), 'user_refresh_tokens', ['token_jti'], unique=True)
    op.create_index(op.f('ix_user_refresh_tokens_user_id'), 'user_refresh_tokens', ['user_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('events_id', sa.UUID(), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'events_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_user_refresh_tokens_user_id'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_token_jti'), table_name='user_refresh_tokens')
    op.drop_table('user_refresh_tokens')
    op.drop_index(op.f('ix_user_backup_codes_user_id'), table_name='user_backup_codes')
    op.drop_index(op.f('ix_user_backup_codes_id'), table_name='user_backup_codes')
    op.drop_table('user_backup_codes')
    op.drop_index('uq_solicitacao_pendente_usuario', table_name='solicitacoes_militancia', postgresql_where=sa.text("status = 'PENDENTE'"))
    op.drop_index(op.f('ix_solicitacoes_militancia_user_id'), table_name='solicitacoes_militancia')
    op.drop_index(op.f('ix_solicitacoes_militancia_status'), table_name='solicitacoes_militancia')
    op.drop_index(op.f('ix_solicitacoes_militancia_id'), table_name='solicitacoes_militancia')
    op.drop_table('solicitacoes_militancia')
    op.drop_index('uq_cartao_pendente_usuario', table_name='solicitacoes_cartao', postgresql_where=sa.text("status = 'PENDENTE'"))
    op.drop_index(op.f('ix_solicitacoes_cartao_user_id'), table_name='solicitacoes_cartao')
    op.drop_index(op.f('ix_solicitacoes_cartao_status'), table_name='solicitacoes_cartao')
    op.drop_index(op.f('ix_solicitacoes_cartao_id'), table_name='solicitacoes_cartao')
    op.drop_table('solicitacoes_cartao')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_destinatario'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_admin_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_noticias_slug'), table_name='noticias')
    op.drop_index(op.f('ix_noticias_id'), table_name='noticias')
    op.drop_table('noticias')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_cartao_militantes_user_id'), table_name='cartao_militantes')
    op.drop_index(op.f('ix_cartao_militantes_militante_numero'), table_name='cartao_militantes')
    op.drop_index(op.f('ix_cartao_militantes_id'), table_name='cartao_militantes')
    op.drop_table('cartao_militantes')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_scopes_id'), table_name='admin_scopes')
    op.drop_table('admin_scopes')
    op.drop_index(op.f('ix_users_nif'), table_name='users')
    op.drop_index(op.f('ix_users_militante_numero'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissoes')
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_provincias_nome_provincia'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_id'), table_name='provincias')
    op.drop_table('provincias')
    op.drop_index(op.f('ix_permissoes_id'), table_name='permissoes')
    op.drop_table('permissoes')
    op.drop_table('noticia_categorias')
    # ### end Alembic commands ###
