"""add os campos para validacao de das politicas e termos de acordo a APD

Revision ID: e5168b07ccbd
Revises: 5c756d3e7a3f
Create Date: 2026-10-02 17:37:27.222545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5168b07ccbd'
down_revision: Union[str, Sequence[str], None] = '5c756d3e7a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('consentimento_lpd', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('concedido_em', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('versao_politica_apd', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'versao_politica_apd')
    op.drop_column('users', 'concedido_em')
    op.drop_column('users', 'consentimento_lpd')
    # ### end Alembic commands ###
